# Jekyll Specific Stuff
markdown: rdiscount
pygments: true
paginate: 10 # the number of post per page
paginate_path: 'blog/page:num'
relative_permalinks: false
rdiscount:
  extensions: [smart]

# User Options
name: ex2D
baseurl: /ex2d  # Leave this blank unless you are using a directory other than the root directory (Do not use a trailing slash '/')
description: 'A Sprite Engine For Unity That Is Most Performing And Elegant. Now At 2.0.'
email: studio@ex-dev.com 
twitter: abitgames 
icon_url: /images/logo.png 
disqus_shortname: 
google_analytics: UA-8694664-5 

# ex2D links
unity_discussion: http://forum.unity3d.com/threads/196466-ex2D-v2-Fast-and-Elegant-Sprite-Engine-for-Unity
ex2d_forum: http://forum.ex-dev.com/viewforum.php?f=4&sid=8f2a0aafbd0c31b374b34b99e3f29163
ex2d_v1_web: http://exdev.webfactional.com/ex2d

# Color Options
text_color: '#424242'
accent_color: '#FF9900'
hover_color: '#a7543f'
subtle_color: '#999999'
subtle_border: '#e9e9e9'
title_color: '#222222'
text_on_accent_color: '#ffffff'
header_background: '#3299BB'
header_text_color: '#dfe6ec'
header_accent_color: '#E9E9E9'
header_title_color: '#E9E9E9'
header_subtle_color: '#BCBCBC'
header_subtle_border: '#BCBCBC'
background: '#F9F9F9'
post_background:

# Footer
footer_title: 
footer_description: 
social_links_title: 
github_url: https://github.com/exdev/ex2d 
flickr_url: 
instagram_url: 
vimeo_url: 
facebook_url: 
google_plus_url: 
pinterest_url: 
tumblr_url: 
linkedin_url: 
dribbble_url: 
lastfm_url: 
rdio_url: 
spotify_url: 
skype_url: 
soundcloud_url: 
behance_url: 
