# Jekyll Specific Stuff
markdown: rdiscount
pygments: true
permalink: news/:title
paginate: 10 # the number of post per page
paginate_path: 'news/page:num'
rdiscount:
  extensions: [smart]

# User Options
name: ex2D
baseurl: /ex2d_doc  # Leave this blank unless you are using a directory other than the root directory (Do not use a trailing slash '/')
description: 'A Sprite Engine For Unity That Is Both Performing And Elegant.'
email: studio@ex-dev.com 
twitter: abitgames 
icon_url: /images/logo.png 
disqus_shortname: 

# Color Options
text_color: '#424242'
accent_color: '#FF9900'
hover_color: '#a7543f'
subtle_color: '#999999'
subtle_border: '#e9e9e9'
title_color: '#222222'
text_on_accent_color: '#ffffff'
header_background: '#3299BB'
header_text_color: '#dfe6ec'
header_accent_color: '#E9E9E9'
header_title_color: '#E9E9E9'
header_subtle_color: '#BCBCBC'
header_subtle_border: '#BCBCBC'
background: '#F9F9F9'
post_background:

# Footer
footer_title: 
footer_description: 
social_links_title: 
github_url: https://github.com/jwu/ex2d_doc 
flickr_url: 
instagram_url: 
vimeo_url: 
facebook_url: 
google_plus_url: 
pinterest_url: 
tumblr_url: 
linkedin_url: 
dribbble_url: 
lastfm_url: 
rdio_url: 
spotify_url: 
skype_url: 
soundcloud_url: 
behance_url: 
